apiVersion: v1
kind: ConfigMap
metadata:
  name: jnginx-configmap
  namespace: ingress-nginx
data:
  nginx.conf: |
    worker_processes 4;
    worker_rlimit_nofile 40000;

    events {
        worker_connections 8192;
    }

    http {
        upstream rke {
            server pi-1.jabl3s.home;
            server pi-2.jabl3s.home;
            server pi-3.jabl3s.home;
            server pi-4.jabl3s.home;
        }
        map $http_upgrade $connection_upgrade {
            default Upgrade;
            ''      close;
        }
        server {
            listen 80;
            listen 443 ssl;
            server_name *.jabl3s.home;
            return 301 https://$server_name$request_uri;
            location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Port $server_port;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://rke;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_read_timeout 900s;
                proxy_buffering off;
            }
        }
    }